-- Weather Observation Station 4

SELECT COUNT(city) - COUNT(DISTINCT city)
FROM STATION;

-- 동명 동물 수 찾기

SELECT NAME, count(name) as COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME ASC;