SELECT B.L AS HOUR,
    NVL(A.COUNT, 0) AS COUNT
FROM (
    SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24')
    ORDER BY TO_CHAR(DATETIME, 'HH24')
) A,
(
    SELECT LEVEL-1 AS L
    FROM DUAL
    CONNECT BY LEVEL <= 24
) B
WHERE A.HOUR(+) = B.L
ORDER BY B.L;