-- 코드를 입력하세요
SELECT A.NAME, A.DATETIME
FROM (
    SELECT INS.NAME AS NAME, INS.DATETIME AS DATETIME
    FROM ANIMAL_INS INS LEFT OUTER JOIN ANIMAL_OUTS OUTS ON (INS.ANIMAL_ID = OUTS.ANIMAL_ID)
    WHERE OUTS.ANIMAL_ID IS NULL
    ORDER BY INS.DATETIME ASC
) A
WHERE ROWNUM <= 3