-- 1

SELECT D.DEPTNO, D.DNAME,
    E.EMPNO, E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND 
    SAL > 2000;

SELECT D.DEPTNO, D.DNAME,
    E.EMPNO, E.ENAME, E.SAL
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE SAL > 2000;

-- 2

SELECT D.DEPTNO, D.DNAME, AVG(SAL), MAX(SAL), MIN(SAL), COUNT(*)
FROM DEPT D JOIN EMP E ON (D.DEPTNO = E.DEPTNO)
GROUP BY D.DEPTNO, D.DNAME;

SELECT D.DEPTNO, D.DNAME, AVG(SAL), MAX(SAL), MIN(SAL), COUNT(*)
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

-- 3

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM DEPT D LEFT OUTER JOIN EMP E ON (D.DEPTNO = E.DEPTNO);

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO(+);

-- 4

SELECT D.DEPTNO, D.DNAME,
    E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO,
    S.LOSAL, S.HISAL, S.GRADE,
    E2.EMPNO, E2.ENAME
FROM DEPT D LEFT OUTER JOIN EMP E ON (D.DEPTNO = E.DEPTNO)
    LEFT OUTER JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
    LEFT OUTER JOIN EMP E2 ON (E.MGR = E2.EMPNO)
ORDER BY D.DEPTNO, D.DNAME, E.EMPNO;

