-- 보호소에서 중성화한 동물

SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A LEFT OUTER JOIN ANIMAL_OUTS B ON (A.ANIMAL_ID = B.ANIMAL_ID)
WHERE A.SEX_UPON_INTAKE LIKE 'Intact%'
    AND B.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY A.ANIMAL_ID;

-- 입양 시각 구하기(2)

WITH
A AS
    (SELECT LEVEL-1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24),
B AS
    (SELECT COUNT(*) AS COUNT, TO_CHAR(DATETIME, 'HH24') AS HOUR
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24'))

SELECT A.HOUR,
    NVL(B.COUNT, 0)
FROM A LEFT OUTER JOIN B ON (A.HOUR = B.HOUR)
ORDER BY A.HOUR

-- 중성화 여부 파악하기

SELECT ANIMAL_ID, NAME,
    CASE
        WHEN SEX_UPON_INTAKE LIKE 'Neutered%' THEN 'O'
        WHEN SEX_UPON_INTAKE LIKE 'Spayed%' THEN 'O'
        ELSE 'X'
    END AS 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- 우유와 요거트가 담긴 장바구니

WITH A AS
(
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
),
B AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
)

SELECT A.CART_ID
FROM A JOIN B ON (A.CART_ID = B.CART_ID)
ORDER BY A.CART_ID