-- 코드를 입력하세요
SELECT NAME, COUNT
FROM (
    SELECT NAME, COUNT(NAME) AS COUNT
    FROM ANIMAL_INS
    GROUP BY NAME
    ORDER BY NAME ASC
)
WHERE COUNT >= 2;


SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME ASC;