-- oracle

SELECT HOUR, COUNT
FROM (
SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(TO_CHAR(DATETIME, 'HH24')) AS COUNT
 FROM ANIMAL_OUTS
 GROUP BY TO_CHAR(DATETIME, 'HH24')
 ORDER BY TO_CHAR(DATETIME, 'HH24')
)
WHERE HOUR >= 9 AND HOUR < 20;

SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(TO_CHAR(DATETIME, 'HH24')) AS COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') >= 9 AND TO_CHAR(DATETIME, 'HH24') < 20
ORDER BY HOUR ASC;