-- Oracle

-- 둘 다 됨.
-- Aged 문자열에 "" 안되고, ''만 됨.
-- 문자열은 당연히 대소문자 구분
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION NOT IN 'Aged'
ORDER BY ANIMAL_ID ASC;

SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged'
ORDER BY ANIMAL_ID ASC;