-- 코드를 입력하세요
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS JOIN ANIMAL_OUTS OUTS ON (INS.ANIMAL_ID = OUTS.ANIMAL_ID)
WHERE UPPER(INS.SEX_UPON_INTAKE) LIKE 'INTACT%'
    AND (UPPER(OUTS.SEX_UPON_OUTCOME) LIKE 'SPAYED%'
         OR
         UPPER(OUTS.SEX_UPON_OUTCOME) LIKE 'NEUTERED%')
ORDER BY ANIMAL_ID;