-- 코드를 입력하세요
SELECT C.MONTH, C.NAME, C.COUNT
FROM (
        SELECT TO_CHAR(B.CREATED_AT, 'MM') AS MONTH, A.NAME AS NAME, COUNT(*) AS COUNT,
            RANK() OVER(PARTITION BY TO_CHAR(B.CREATED_AT, 'MM') ORDER BY COUNT(*) DESC) AS RA
        FROM PLACES A JOIN PLACE_REVIEWS B ON (A.ID = B.PLACE_ID)
        WHERE TO_CHAR(B.CREATED_AT, 'YYYYMMDD') BETWEEN '20180101' AND '20181231'
        GROUP BY TO_CHAR(B.CREATED_AT, 'MM'), A.NAME
        ORDER BY TO_CHAR(B.CREATED_AT, 'MM'), COUNT DESC
    ) C
WHERE RA = 1
ORDER BY C.MONTH, C.NAME;